### ISSUE TITLE
Feature request: Delete a consumable item that has `Destroy On Empty` checked when consuming its last remaining limited uses through an optional babonus.

### ISSUE THREAD

**Issue by MaxPat931** [krbz999/babonus#216]
https://user-images.githubusercontent.com/86370342/235489804-9f708275-d254-4f25-8cca-66a8508b8a94.mp4

**Comment by krbz999** [comment]
### Implemented feature:
If the babonus consumes an item's uses (not quantity) and the consumption would bring it to 0 uses, and said item has `system.uses.autoDestroy = true` (i.e "Destroy on Empty"), then the user will be prompted for destroying the item instead of having the item updated. Declining the prompt results in no changes made.

There is normally not a confirm prompt with consumable items, but this is more in line with how the module consumes active effects.

**Comment by MaxPat931** [comment]
Thank you!
