### ISSUE TITLE
[BUG] Minimum system requirement value is incorrect

### ISSUE THREAD

**Issue by SoryKnight** [krbz999/babonus#415]
**Describe the bug**
Last commit ca2c412 updates the minimum system requirement compatibility to version 3.2.0 of dnd5e but the last version released of dnd5e is 3.1.2 (https://foundryvtt.com/packages/dnd5e) which breaks the module once it is updated

**To Reproduce**
1. Update module in foundry
2. Start new world (or start any existing world)
3. In the module management section, "Build-a-bonus" appear disabled and it is unselectable and the system requirement message appears

**Expected behavior**
The module shall be selectable in the management section

**Setup**
Describe your foundry setup.
- Build-a-Bonus version: 11.11.0
- Foundry core version and build: Version 11 stable Compilation 315
- Other modules disabled? Yes

**Comment by krbz999** [comment]
The release notes state that the minimum version has been bumped to 3.2. This is an intentional, because that is what it requires. Users are expected to not update if they do not wish to use that system version (which is forthcoming).

You can install the previous version of the module in the meantime.
