### ISSUE TITLE
Feature Request: Tie the use of an optional bonus to quantity or limited uses of an item

### ISSUE THREAD

**Issue by Ward-Ceyssens** [krbz999/babonus#51]
It would be nice to have some way to create "on first hit in turn" or "once per turn" bonuses, like the ones from a Rangers Favored Foe , a Zealot Barbarians Divine Fury or a Rogues Sneak Attack. Currently this can only be partially done using midiqol optional flags but it leaves a lot to be desired and this seems to be something that fits the scope of this module

**Comment by krbz999** [comment]
you can just turn the bonus off.

**Comment by Ward-Ceyssens** [comment]
can't the same can be said for every other filter in this module?

**Comment by krbz999** [comment]
no, they act as filters to prevent a bonus from being applied where they should not. the scope of this module is to expand (and narrow) the application of bonuses to help make more fun bonuses or magic items rather than a dull "+1 to attack/damage rolls".

what you are asking for can be done easily with other modules already. I suggest Effect Macro. as such I won't consider this request.

**Comment by krbz999** [comment]
This has been reconsidered for 10.3.0 with a bit of reframing. While I don't consider automated behavior such as applying a bonus only for the first attack of a turn within the scope of this module (nor would it be possible with this module alone), limiting the usage of a bonus, tied it to an item property such as the Limited Uses or Quantity, is very much doable.

**Comment by thatlonelybugbear** [comment]
Good idea!
The "automation" part will be (more) easily achieved with a simple Effect Macro, used to recover the relevant uses when needed.
