### ISSUE TITLE
Add option to use grid spaces when measuring aura radius, and to not artificially increase the size of the radius due to token size

### ISSUE THREAD

**Issue by 9ryex5** [krbz999/babonus#56]
Allow for the Aura Range to support different system diagonal movement rules.
As well as better calculations using different heights.

**Comment by the-real-orson** [comment]
Question of curiosity:  why would you use diagonal movement measurement rules for the aura?  An aura is a radius of effect, doesn't have anything to do with movement.  If, for example, you were playing in dnd5e base PHB movement rules, a token that is '20 ft. of movement' away on a diagonal is actually 30  ft. away.  So for an aura to include the creature, the aura radius must be at least 30 ft., possibly a little less if you rule that auras radiate from the edges of a creature rather than its center.

**Comment by 9ryex5** [comment]
My bad, I'm used to mix diagonal movement rules and templates/radius since I always play using the Euclidean system and the results are the same. What I meant is that the Aura Range from Build a Bonus differs from foundry templates. In the image there are two templates (radius 10 ft. and 30 ft.), Build a Bonus is applying the bonus if a token is on the white squares, even though they are outside of the template.
![image](https://user-images.githubusercontent.com/43207603/199622288-a29eb111-f35a-411a-a524-b3023eedce83.png)

**Comment by krbz999** [comment]
This is intended.
- If the aura is originating from a token, Babonus calculates the distance from the edge of the token's occupied cell(s).
- For auras on templates, Babonus instead uses any highlighted cells since it originates from a point, not an area.

Then, additionally, Babonus calculates the height distance between two tokens, and uses non-Euclidean measurements. In other words, the direct distance is the maximum of the vertical and horizontal distances (rather than applying Pythagoras). I feel this is standard at most tables.

**Comment by kiligir** [comment]
I would be all for an option to calculate based on a square shape originating from the token's center. We can get into the minutiae of how this game was actually designed for theater of the mind when it was set up and that the movement rules are a simplification of previous 3.5/Pathfinder 5/10/5 alternating, and we could also talk about how the template system (which is terrible for non circle, non rectangle templates) doesn't work well with this 5-foot diagonal non-Euclidean thing. At the end of the day, if my players drag a ruler from their token two spaces NE and it says 10 feet, that should be "within 10 feet," as Aura of Protection states. Not by default, I actually think your solution is elegant, but an option would be highly useful.

Also, not rounding my auras would be neat, too. I can open this separately if I need to.

**Comment by krbz999** [comment]
Tagging as wontfix. Won't be looked at until v12.

**Comment by krbz999** [comment]
Adding this to the v12 milestone since it should now be fairly trivial to implement.
